[[researchers]]
name= "Giovanni Petri"
title= "Principal Researcher"
bio= "Principal Researcher at CENTAI Institute working on topological approaches to complex networks and their underlying geometry, with special attention to the topology of brain structure and dynamics."
avatar="static/faces/giovanni_petri.jpeg"
url="https://lordgrilo.github.io"

[[researchers]]
name= "Maxime Lucas"
title= "Post-Doc Researcher"
bio="Maxime researches complex systems and their application to the life sciences. Physicist, Belgian, likes a good (or bad) pun."
avatar="static/faces/maxime_lucas.jpeg"
url="https://maximelucas.github.io"

[[researchers]]
name= "Simone Poetto"
title= "PhD Student"
bio="Simone is a physicist with a research focus on artificial intelligence and neuroscience. When not in the lab, he loves mountains and hiking."
avatar="static/faces/simone_poetto.jpeg"
url="https://simonepoetto.github.io"

[[researchers]]
name= "Marco Nurisso"
title= "PhD Student"
bio="Ph.D. student in Pure and Applied Mathematics interested in applied topology and its intersections with artificial intelligence and complex systems."
avatar="static/faces/marco_nurisso.jpeg"
url=""

[[researchers]]
name= "António Leitão"
title= "Junior Researcher"
bio="Mathematician focused on appplied algebraic topology, topological data analysis and machine learning."
avatar="static/faces/antonio_leitao.jpeg"
url="https://antonio-leitao.github.io"

[[researchers]]
name= "Napat Kiatjaroonlert"
title= "Junior Researcher"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/napat_kiatjaroonlert.jpeg"
url=""

[[researchers]]
name= "Matteo Neri"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/matteo_neri.jpeg"
url=""

[[researchers]]
name= "Marta Morandini"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/marta_morandini.jpeg"
url=""


[[researchers]]
name= "Sara Cavuoti Cabanillas"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/sara_cabanillas.jpeg"
url=""

[[researchers]]
name= "Thomas Robiglio"
title= "NPC"
bio="He is an physicist interested in the study of complex systems with tools from Statistical Physics and Network Science."
avatar="static/faces/thomas_robiglio.jpeg"
url="https://thomasrobiglio.github.io"

[[researchers]]
name= "Alessandra Brondetta"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/alessandra_brondetta.jpeg"
url=""

[[researchers]]
name= "Noemi Aime"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/noemi_aime.jpeg"
url=""




