[[researchers]]
name= "Giovanni Petri"
title= "Principal Researcher"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/giovanni_petri.jpeg"
url="https://lordgrilo.github.io"

[[researchers]]
name= "Maxime Lucas"
title= "Post-Doc Researcher"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/maxime_lucas.jpg"
url="https://maximelucas.github.io"

[[researchers]]
name= "Simone Poetto"
title= "PhD Student"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/simone_poetto.jpg"
url=""

[[researchers]]
name= "Marco Nurisso"
title= "PhD Student"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/marco_nurisso.jpeg"
url=""

[[researchers]]
name= "António Leitão"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/antonio_leitao.jpeg"
url="https://antonio-leitao.github.io"

[[researchers]]
name= "Napat Kiatjaroonlert"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/napat_kiatjaroonlert.jpeg"
url=""

[[researchers]]
name= "Matteo Neri"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="https://www.swashvillage.org/storage/img/images_1/danny-devito-biography.jpg"
url=""

[[researchers]]
name= "Marta Morandini"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/marta_morandini.jpeg"
url=""

[[researchers]]
name= "Sara Cavuoti Cabanillas"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="https://www.swashvillage.org/storage/img/images_1/danny-devito-biography.jpg"
url=""

[[researchers]]
name= "Thomas Robiglio"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/thomas_robiglio.jpeg"
url=""

[[researchers]]
name= "Noemi Aime"
title= "NPC"
bio="This person does this and that it was them that started this and that is now doing that. Reach by here or there."
avatar="static/faces/noemi_aime.jpeg"
url=""



