[[researchers]]
name= "Giovanni Petri"
tag= "giovanni_petri"
title= "PI"
bio= "Professor at Network Science Institute, Northeastern University London. Principal Researcher at CENTAI.  
He works on topological approaches to complex networks and their underlying geometry, with special attention to the topology of brain structure and dynamics."
avatar="/static/people/giovanni_petri.jpg"
hoverAvatar="/static/people/giovanni_petri_alt.jpg"
url="https://lordgrilo.github.io"
github="http://www.github.com/lordgrilo"
email="giovanni.petri@northeastern.edu"
twitter="https://x.com/lordgrilo"
scholar="https://scholar.google.com/citations?hl=en&user=jb__2PIAAAAJ"
linkedin="https://www.linkedin.com/in/giovannipetri/"
orcid="https://orcid.org/0000-0003-1847-5031"

[[researchers]]
name= "Marilyn Gatica"
tag= "marilyn_gatica"
title= "Post-Doc Researcher @ Network Science Institute"
bio=""
avatar="/static/people/marilyn_gatica.jpg"
hoverAvatar="/static/people/marilyn_gatica.jpg"
url="https://www.nulondon.ac.uk/faculty/marilyn-gatica/"

[[researchers]]
name= "Andrea Santoro"
tag= "andrea_santoro"
title= "Post-Doc Researcher @ CENTAI Institute"
bio="Postdoctoral researcher at CENTAI. Currently, his work involves developing topological approaches to infer higher-order dependencies in multivariate time series, with applications in brain data and economics."
avatar="/static/people/andrea_santoro.jpg"
hoverAvatar="/static/people/andrea_santoro.jpg"
url="https://andresantoro.github.io/"
github="https://github.com/andresantoro"
email="andrea.santoro@centai.eu"
twitter="https://x.com/andreasantor0"
scholar="https://scholar.google.co.uk/citations?user=gGSh6oEAAAAJ&hl=en"
linkedin="https://www.linkedin.com/in/andrea-santoro-17064592/"
orcid="https://orcid.org/0000-0001-7959-2958"




[[researchers]]
name= "Simone Poetto"
tag= "simone_poetto"
title= "PhD Student @ CENTAI Institute + Nikolaus Kopernicus University"
bio="Simone is a physicist with a research focus on artificial intelligence and neuroscience. When not in the lab, he loves mountains and hiking."
avatar="/static/people/simone_poetto.jpg"
hoverAvatar="/static/people/simone_poetto_alt.jpg"
url="https://simonepoetto.github.io"

[[researchers]]
name= "Marco Nurisso"
tag= "marco_nurisso"
title= "PhD Student @ CENTAI Institute + Polytechnic University of Turin"
bio="PhD student in Pure and Applied Mathematics interested in applied topology and its intersections with artificial intelligence and complex systems."
avatar="/static/people/marco_nurisso.jpg"
hoverAvatar="/static/people/marco_nurisso_alt.jpg"
url=""

[[researchers]]
name= "Jesseba Fernando"
tag= "jesseba_fernando"
title= "PhD Student @ Network Science Institute"
bio= "Jesseba researches neuronal dynamics of learning through the lens of network science and complex systems."
avatar="/static/people/jesseba_fernando.jpg"
hoverAvatar="/static/people/jesseba_fernando_alt.jpg"
url="https://jesseba.github.io/"
github="http://www.github.com/jesseba"
email="fernando.je@northeastern.edu"
twitter="https://x.com/richlyn_jesseba"
scholar="https://scholar.google.com/citations?hl=en&user=R4X-c5oAAAAJ"

[[researchers]]
name= "Davide Orsenigo"
tag= "davide_orsenigo"
title= "PhD Student @ Università degli Studi di Torino"
bio="PhD student in Neuroscience, studying the brain through the lens of higher-order interactions and information theory."
avatar="/static/people/davide_orsenigo.jpg"
hoverAvatar=""
url=""

[[researchers]]
name= "Henrique M. Borges"
tag= "henriques_borges"
title= "PhD Student @ Network Science Institute"
bio= "Henrique is a physicist converted into a network scientist. He is currently trying to understand the origin and impact of group interactions on coordination, communication, and decision-making"
avatar="/static/people/henrique_borges.jpg"
hoverAvatar="/static/people/henrique_borges.jpg"
url="https://henrique-borges.github.io"
scholar="https://scholar.google.com/citations?user=of9Gx24AAAAJ"

[[researchers]]
name= "Raj Deshpande"
tag= "raj_deshpande"
title= "PhD Student @ Network Science Institute"
bio= ""
avatar="/static/people/raj_deshpande.jpg"
hoverAvatar="/static/people/raj_deshpande.jpg"
url=""

[[researchers]]
name= "Pierrick Leroy"
tag= "pierrick_leroy"
title= "PhD Student @ Polytechnic of Turin"
bio= ""
avatar="/static/people/pierrick_leroy.jpg"
hoverAvatar="/static/people/pierrick_leroy.jpg"
url=""

[[researchers]]
name= "Elisabetta Salvai"
tag= "elisabetta_salvai"
title= "PhD @ University of Copenhagen"
bio= "PhD student researching fairness in network rankings and gender representation in computer science and physics conferences."
avatar="static/people/elisabetta_salvai.jpg"
hoverAvatar="static/people/elisabetta_salvai_alt.jpg"
url=""
github="https://github.com/elisabettasalvai"
email="elsa@sodas.ku.dk"
twitter="https://x.com/elisalvai"
linkedin="https://www.linkedin.com/in/elisabetta-salvai-069a912ba/"
orcid="https://orcid.org/0009-0009-1218-8526"

[[researchers]]
name= "Giulia Lorenzini"
tag= "giulia_lorenzini"
title= "MSc Student @ Turin University + CENTAI Institute"
bio=""
avatar="/static/people/giulia_lorenzini_new.jpg"
hoverAvatar="/static/people/giulia_lorenzini_new.jpg"
url=""

[[researchers]]
name= "Francesco Guadagnuolo"
tag= "francesco_guadagnuolo"
title= "MSc Student @ EPFL"
bio=""
avatar="/static/people/francesco_maria_guadagnuolo.jpg"
hoverAvatar="/static/people/francesco_maria_guadagnuolo_new.jpg"
url=""

[[alumni]]
name= "Maxime Lucas"
tag= "maxime_lucas"
title= "Post-Doc Researcher"
bio="Maxime researches complex systems and their application to the life sciences. Physicist, Belgian, likes a good (or bad) pun."
avatar="/static/people/maxime_lucas.jpg"
hoverAvatar="/static/people/maxime_lucas_alt.jpg"
url="https://maximelucas.github.io"

[[alumni]]
name= "Leonardo Federici"
tag= "leonardo_federici"
title= "MSc Student"
bio= ""
avatar="/static/people/leonardo_federici.jpg"
hoverAvatar="/static/people/leonardo_federici.jpg"
url=""

[[alumni]]
name= "Alessandra Brondetta"
tag= "alessandra_brondetta"
title= "PhD Student @ Osnabrück University"
bio=""
avatar="/static/people/alessandra_brondetta.jpg"
hoverAvatar="/static/people/alessandra_brondetta_alt.jpg"
url=""

[[alumni]]
name= "Brendan Matulis"
tag= "brendan_matulis"
title= "BSc Student @ Northeastern University"
bio= ""
avatar="/static/people/brendan_matulis.jpg"
hoverAvatar="/static/people/brendan_matulis.jpg"
url=""

[[alumni]]
name= "Napat Kiatjaroonlert"
tag= "napat_kiatjaroonlert"
title= "MSc Student"
bio=""
avatar="static/people/napat_kiatjaroonlert.jpg"
hoverAvatar="static/people/napat_kiatjaroonlert_alt.jpg"
url=""

[[alumni]]
name= "Matteo Neri"
tag= "matteo_neri"
title= "PhD Student @ Aix-Marseille University"
bio=""
avatar="/static/people/matteo_neri.jpg"
hoverAvatar="/static/people/matteo_neri.jpg"
url=""

[[alumni]]
name= "Marta Morandini"
tag= "marta_morandini"
title= "PhD Student @ Aix-Marseille University"
bio="Mathematician in progress interested in mixing disciplines. Newborn in neuroscience, currently working on applied topology and complex systems."
avatar="static/people/marta_morandini.jpg"
hoverAvatar="static/people/marta_morandini_alt.jpg"
url=""

[[alumni]]
name= "Cosimo Agostinelli"
tag= "cosimo_agostinelli"
title="PhD Student @ Aix-Marseille University"
bio="Former phisicist interested in complex and higher-order networks, group dynamics and any physics-related approach to these topics."
avatar="/static/people/cosimo_agostinelli.jpg"
hoverAvatar="/static/people/cosimo_agostinelli_alt.jpg"
url=""

[[alumni]]
name= "Noemi Aime"
tag= "noemi_aime"
title="MSc Student"
bio=""
avatar="static/people/noemi_aime.jpg"
hoverAvatar="static/people/noemi_aime_alt.jpg"
url=""

[[alumni]]
name= "António Leitão"
tag= "antonio_leitao"
title= "PhD Student @ Scuola Normale Superiore di Pisa"
bio="Mathematician focused on appplied algebraic topology, topological data analysis and machine learning."
avatar="static/people/antonio_leitao.jpg"
hoverAvatar="static/people/antonio_leitao_alt.jpg"
url="https://antonio-leitao.github.io"

[[alumni]]
name= "Alice Patania"
tag= "alice_patania"
title="Assistant Professor @ University of Vermont"
bio=""
avatar="static/people/alice_patania.jpg"
hoverAvatar="static/people/alice_patania.jpg"
url="https://alpatania.github.io/"

[[alumni]]
name= "Sara Cavuoti Cabanillas"
tag= "sara_cavuoti_cabanillas"
title= "PhD Student @ University of Parma"
bio=""
avatar="static/people/sara_cabanillas.jpg"
hoverAvatar="static/people/sara_cabanillas.jpg"
url=""

[[alumni]]
name= "Thomas Robiglio"
tag= "thomas_robiglio"
title= "PhD Student @ Central European University"
bio="He is an physicist interested in the study of complex systems with tools from Statistical Physics and Network Science."
avatar="static/people/thomas_robiglio.jpg"
hoverAvatar="static/people/thomas_robiglio_alt.jpg"
url="https://thomasrobiglio.github.io"

[[alumni]]
name= "Asia Maurich Novelli"
tag= "asia_maurich_novelli"
title="MSc Student"
bio=""
avatar="/static/people/asia_maurich_novelli.jpg"
hoverAvatar="/static/people/asia_maurich_novelli.jpg"
url=""

[[alumni]]
name= "Davide Coppes"
tag= "davide_coppes"
title="MSc Student"
bio=""
avatar="/static/people/davide_coppes.jpg"
hoverAvatar="/static/people/davide_coppes.jpg"
url=""

[[alumni]]
name= "Jacob Billings"
tag= "jacob_billings"
title="Postdoc @ Academy of Sciences of the Czech Republic"
bio=""
avatar="/static/people/jacob_billings.jpg"
hoverAvatar="/static/people/jacob_billings.jpg"
url=""
