[[researchers]]
name= "Giovanni Petri"
tag= "giovanni_petri"
title= "Principal Researcher"
bio= "Principal Researcher at CENTAI Institute working on topological approaches to complex networks and their underlying geometry, with special attention to the topology of brain structure and dynamics."
avatar=""
url="https://lordgrilo.github.io"

[[researchers]]
name= "Maxime Lucas"
tag= "maxime_lucas"
title= "Post-Doc Researcher"
bio="Maxime researches complex systems and their application to the life sciences. Physicist, Belgian, likes a good (or bad) pun."
avatar=""
url="https://maximelucas.github.io"

[[researchers]]
name= "Marilyn Gatica"
tag= "marilyn_gatica"
title= "Post-Doc Researcher @ Northeastern University, London"
bio=""
avatar=""
url=""

[[researchers]]
name= "Simone Poetto"
tag= "simone_poetto"
title= "PhD Student"
bio="Simone is a physicist with a research focus on artificial intelligence and neuroscience. When not in the lab, he loves mountains and hiking."
avatar=""
url="https://simonepoetto.github.io"

[[researchers]]
name= "Marco Nurisso"
tag= "marco_nurisso"
title= "PhD Student"
bio="PhD student in Pure and Applied Mathematics interested in applied topology and its intersections with artificial intelligence and complex systems."
avatar=""
url=""

[[researchers]]
name= "Davide Orsenigo"
tag= "davide_orsenigo"
title= "PhD Student @ Università degli Studi di Torino"
bio="PhD student in Neuroscience, studying the brain through the lens of higher-order interactions and information theory."
avatar=""
url=""

[[researchers]]
name= "Alessandra Brondetta"
tag= "alessandra_brondetta"
title= "PhD Student @ Osnabrück University"
bio=""
avatar=""
url=""

[[researchers]]
name= "Elisabetta Salvai"
tag= "elisabetta_salvai"
title= "Research assistant @ University of Copenhagen"
bio= "PhD student wannabe, researching fairness in network rankings and science conferences."
avatar="static/faces/Elisabetta_Salvai.jpg"
url=""

[[researchers]]
name= "Henrique M. Borges"
tag= "henriques_borges"
title= "PhD Student @ Northeastern University, London"
bio= "Henrique is a physicist converted into a network scientist. He is currently trying to understand the origin and impact of group interactions on coordination, communication, and decision-making"
avatar=""
url=""

[[researchers]]
name= "Raj Deshpande"
tag= "raj_deshpande"
title= "PhD Student @ Northeastern University, London"
bio= ""
avatar=""
url=""

[[researchers]]
name= "Jesseba Fernando"
tag= "jesseba_fernando"
title= "PhD Student"
bio= ""
avatar=""
url=""

[[alumni]]
name= "Leonardo Federici"
tag= "leonardo_federici"
title= "MSc Student"
bio= ""
avatar=""
url=""

[[alumni]]
name= "Brendan Matulis"
tag= "brendan_matulis"
title= "BSc Student"
bio= ""
avatar=""
url=""

[[alumni]]
name= "Napat Kiatjaroonlert"
tag= "napat_kiatjaroonlert"
title= "MSc Student"
bio=""
avatar="static/people/napat_kiatjaroonlert.jpeg"
url=""

[[alumni]]
name= "Matteo Neri"
tag= "matteo_neri"
title= "PhD Student @ Aix-Marseille University"
bio=""
avatar=""
url=""

[[alumni]]
name= "Marta Morandini"
tag= "marta_morandini"
title= "PhD Student @ Aix-Marseille University"
bio="Mathematician in progress interested in mixing disciplines. Newborn in neuroscience, currently working on applied topology and complex systems."
avatar="static/people/marta_morandini.jpeg"
url=""

[[alumni]]
name= "Cosimo Agostinelli"
tag= "cosimo_agostinelli"
title="PhD Student @ Aix-Marseille University"
bio="Former phisicist interested in complex and higher-order networks, group dynamics and any physics-related approach to these topics."
avatar=""
url=""

[[alumni]]
name= "Noemi Aime"
tag= "noemi_aime"
title="MSc Student"
bio=""
avatar="static/people/noemi_aime.jpeg"
url=""

[[alumni]]
name= "António Leitão"
tag= "antonio_leitao"
title= "PhD Student @ Scuola Normale Superiore di Pisa"
bio="Mathematician focused on appplied algebraic topology, topological data analysis and machine learning."
avatar="static/people/antonio_leitao.jpeg"
url="https://antonio-leitao.github.io"

[[alumni]]
name= "Alice Patania"
tag= "alice_patania"
title="Assistant Professor @ University of Vermont"
bio=""
avatar="static/people/alice_patania.jpeg"
url="https://alpatania.github.io/"

[[alumni]]
name= "Sara Cavuoti Cabanillas"
tag= "sara_cavuoti_cabanillas"
title= "PhD Student @ University of Parma"
bio=""
avatar="static/people/sara_cabanillas.jpeg"
url=""

[[alumni]]
name= "Thomas Robiglio"
tag= "thomas_robiglio"
title= "PhD Student @ Central European University"
bio="He is an physicist interested in the study of complex systems with tools from Statistical Physics and Network Science."
avatar="static/people/thomas_robiglio.jpeg"
url="https://thomasrobiglio.github.io"

[[alumni]]
name= "Asia Maurich Novelli"
tag= "asia_maurich_novelli"
title="MSc Student"
bio=""
avatar=""
url=""
